use_frameworks!

platform :ios, '8.0'

target 'ZBGJModuleA_Example' do
  pod 'ZBGJModuleA', :path => '../'

  target 'ZBGJModuleA_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
